name: Workflow triggered by API Call

on:
  workflow_dispatch:
    inputs:
   #   token:
   #     description: 'Personal Token'
   #     type: string
   #     required: true  
      message:
        description: 'Phrase to be echoed when running the workflow'
        type: string
        required: false
        default: 'Hello World!'

jobs:
  Approval_Gate:
    run-on: ubuntu-latest
    steps:
      - name: Recieve Approval
        shell: bash
        run: 
          echo "Approval required to proceed"
          #approval=$(curl -s -X POST -H "Authorization: token ${{ inputs.token }}" "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/runs/$GITHUB_RUN_ID/approve")

          #if [ "$approval" = "approved"]; then
          #  echo "Approved. Workflow will resume."
          #else
          #  echo "Denied. Exiting workflow."
          #  exit 1
          #fi

  Echo_Message:
    runs-on: ubuntu-latest
    needs: Approval_Gate
    steps:
      - name: Echo Phrase
        run: echo "${{ inputs.message }}"
