name: GitHub Actions Demo
on: 
  workflow_dispatch:
  inputs:
    phrase:
      description: 'Phrase to be echo'ed when running the workflow'
      type: string
      required: false
      default: 'Hello World!'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.phrase }}