name: Workflow triggered by API Call

on:
  workflow_dispatch:
    inputs:
   #   token:
   #     description: 'Personal Token'
   #     type: string
   #     required: true  
      message:
        description: 'to be echoed when running the workflow'
        type: string
        required: false
        default: 'Hello World!'

jobs:
  Echo_Message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Phrase
        run: echo "${{ inputs.message }}"
