name: Workflow to trigger another workflow

on: push

jobs:
  Run_Action:
    runs-on: ubuntu-latest
    environment: 'manual-approval'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the action to trigger the other workflow
        uses: ./.github/actions/api_call
        with:
          token: ${{ secrets.personal_token }}
          workflow: "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/workflows/example-workflow.yml/dispatches"
          message: "THIS WORKS!"