name: Workflow to trigger another workflow

on: push

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action to trigger the other workflow
        uses: apitriggerworkflow/.github/actions/api_call
        with:
          token: ${{ secrets.personal_token }}
          workflow: "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/workflows/example-workflow.yml/dispatches"
          message: "THIS WORKS!"