name: Workflow to trigger another workflow

on: push

jobs:
  Approval_Gate:
    runs-on: ubuntu-latest
    steps:
      - name: Recieve Approval
        shell: bash
        run: 
          echo "Approval required to proceed"
          #approval=$(curl -s -X POST -H "Authorization: token ${{ inputs.token }}" "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/runs/$GITHUB_RUN_ID/approve")

          #if [ "$approval" = "approved"]; then
          #  echo "Approved. Workflow will resume."
          #else
          #  echo "Denied. Exiting workflow."
          #  exit 1
          #fi
  Run_Action:
    runs-on: ubuntu-latest
    needs: Approval_Gate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the action to trigger the other workflow
        uses: ./.github/actions/api_call
        with:
          token: ${{ secrets.personal_token }}
          workflow: "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/workflows/example-workflow.yml/dispatches"
          message: "THIS WORKS!"